### ISSUE TITLE
React Styleguidist

### ISSUE THREAD

**Issue by sapegin** [JulienPradet/pigment-store#1]
Hi!

I’m a creator of [React Styleguidist](https://github.com/sapegin/react-styleguidist). It’s another style guide generator for React. Looks like we already have many features from your roadmap but some things that you’ve implemented are still missed (like this responsive testing toolbar — but we want it).

Have you tried React Styleguidist? If so why did you choose to implement your own solution? Would be nice to have you as a contributor ;-)

**Comment by JulienPradet** [comment]
Hi!

I'm glad you found some features interesting. :)

The main reason I didn't come up getting involved in your repository is because I didn't like how the components were detected. It didn't support Stateless Components either, when I started working on this project. Moreover, I'm meaning to implement automatic visual testing - that's where the testing files are coming from - that didn't seem compatible with react-docgen at the time.

However, if you're interested with the responsive toolbar, I could still contribute since that kind of exchange is exactly what is interesting in open source :)

I'm super excited right now. Thanks :)

**Comment by sapegin** [comment]
Thanks!

Functional components works fine now, not sure about visual testing. We have [some issues](https://github.com/sapegin/react-styleguidist/issues/143) with component detection and HOCs though.

That would be awesome if you could help wish [responsive testing](https://github.com/sapegin/react-styleguidist/issues/133).

**Comment by pquentin** [comment]
@sapegin You asked for help, you got that help the next day. It would be only polite to explain why you did not provide clear actionable feedback on https://github.com/sapegin/react-styleguidist/pull/160. Thanks.

**Comment by sapegin** [comment]
Hi @pquentin! There was a discussion by other contributors. But you’re right it wasn’t ended with any actionable conclusion. I’ll try your branch and think what we should do. Sorry for the delay.

**Comment by pquentin** [comment]
@sapegin For what it's worth, I'm not @JulienPradet :)

**Comment by sapegin** [comment]
@pquentin 😊
